{% set name = "incqueryserver-jupyter" %}
{% set version = "0.21.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/incqueryserver-jupyter-{{ version }}.tar.gz
  sha256: 4a3f386b137dba803989e48923ef716f870eb1f155c222625a197b92102fd04a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - incqueryserver-api-python-client =={{ version }}
    - ipywidgets
    - mms-python-client
    - python >=3.6

test:
  imports:
    - iqs_jupyter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IncQueryLabs/incquery-server-jupyter
  license: Apache-2.0
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: IncQuery Server Client Extensions for Jupyter and Python

extra:
  recipe-maintainers:
    - FuzesiMate
    - pappist
    - abelhegedus
    - ujhelyiz
    - bergmanngabor
