{% set name = "incqueryserver-jupyter" %}
{% set version = "0.18.0.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/incqueryserver-jupyter-{{ version }}.tar.gz
  sha256: 8263fbd4c4124777de2aae80f26e2c5e8487b20e6008e6945ffeff47e6452290

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - incqueryserver-api-python-client ==0.17.1
    - ipywidgets
    - mms-python-client
    - python

test:
  imports:
    - iqs_jupyter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IncQueryLabs/incquery-server-jupyter
  license: Apache-2.0
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: IncQuery Server Client Extensions for Jupyter and Python

extra:
  recipe-maintainers:
    - FuzesiMate
